name: Create Ruleset via javaScript

on:
  workflow_dispatch:

jobs:
  create_ruleset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create Ruleset
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: node src/create-ruleset.js
